/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rate-limits/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acquire rate-limit permits
         * @description This operation is intentionally non-idempotent; do not blindly retry a timed-out check.
         */
        post: operations["check"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LocalCacheView: {
            enabled?: boolean;
            /** Format: int32 */
            expectedMaxInstances?: number;
            /** Format: int64 */
            maxErrorPermits?: number;
            /** Format: int32 */
            maxLeaseSize?: number;
            /** Format: int64 */
            maxLeaseTtlMs?: number;
        };
        PolicyView: {
            /** @enum {string} */
            algorithm?: "TOKEN_BUCKET" | "SLIDING_WINDOW_LOG" | "SLIDING_WINDOW_COUNTER";
            /** @enum {string} */
            failureMode?: "FAIL_OPEN" | "FAIL_CLOSED";
            id?: string;
            /** Format: int32 */
            limit?: number;
            localCache?: components["schemas"]["LocalCacheView"];
            slidingWindow?: components["schemas"]["SlidingWindowView"];
            tokenBucket?: components["schemas"]["TokenBucketView"];
            /** Format: int64 */
            version?: number;
        };
        ProblemDetail: {
            detail?: string;
            /** Format: uri */
            instance?: string;
            properties?: {
                [key: string]: unknown;
            };
            /** Format: int32 */
            status?: number;
            title?: string;
            /** Format: uri */
            type?: string;
        };
        RateLimitCheckRequest: {
            key: string;
            /** Format: int32 */
            permits?: number;
            policyId: string;
        };
        RateLimitCheckResponse: {
            /** @enum {string} */
            algorithm?: "TOKEN_BUCKET" | "SLIDING_WINDOW_LOG" | "SLIDING_WINDOW_COUNTER";
            allowed?: boolean;
            approximate?: boolean;
            degraded?: boolean;
            /** Format: int32 */
            grantedPermits?: number;
            /** Format: int32 */
            limit?: number;
            policyId?: string;
            /** Format: int64 */
            policyVersion?: number;
            /** @enum {string} */
            reason?: "ALLOWED" | "LIMIT_EXCEEDED" | "BACKEND_UNAVAILABLE_FAIL_OPEN" | "BACKEND_UNAVAILABLE_FAIL_CLOSED";
            /** Format: int64 */
            remaining?: number;
            requestId?: string;
            /** Format: int64 */
            resetAtEpochMs?: number;
            /** Format: int64 */
            retryAfterMs?: number;
            /** @enum {string} */
            source?: "REDIS" | "LOCAL_LEASE" | "FAIL_OPEN" | "FAIL_CLOSED";
        };
        SlidingWindowView: {
            /** Format: int32 */
            limit?: number;
            /** Format: int64 */
            windowMs?: number;
        };
        TokenBucketView: {
            /** Format: int32 */
            capacity?: number;
            /** Format: int64 */
            refillPeriodMs?: number;
            /** Format: int32 */
            refillTokens?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PolicyView"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PolicyView"];
                };
            };
        };
    };
    check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateLimitCheckRequest"];
            };
        };
        responses: {
            /** @description Request allowed, including a possible degraded fail-open decision */
            200: {
                headers: {
                    /** @description Decision responses are not cacheable */
                    "Cache-Control"?: unknown;
                    /** @description Configured policy limit */
                    "X-RateLimit-Limit"?: unknown;
                    /** @description Known remaining permits */
                    "X-RateLimit-Remaining"?: unknown;
                    /** @description Reset time in epoch seconds */
                    "X-RateLimit-Reset"?: unknown;
                    /** @description Decision source */
                    "X-RateLimit-Source"?: unknown;
                    /** @description Request correlation identifier */
                    "X-Request-Id"?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitCheckResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Missing or invalid API key when authentication is enabled */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Authenticated caller is not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Unknown policy */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Request body exceeds the service limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Quota denied by the selected policy */
            429: {
                headers: {
                    /** @description Decision responses are not cacheable */
                    "Cache-Control"?: unknown;
                    /** @description Retry delay in whole seconds */
                    "Retry-After"?: unknown;
                    /** @description Configured policy limit */
                    "X-RateLimit-Limit"?: unknown;
                    /** @description Known remaining permits */
                    "X-RateLimit-Remaining"?: unknown;
                    /** @description Reset time in epoch seconds */
                    "X-RateLimit-Reset"?: unknown;
                    /** @description Decision source */
                    "X-RateLimit-Source"?: unknown;
                    /** @description Request correlation identifier */
                    "X-Request-Id"?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitCheckResponse"];
                };
            };
            /** @description Sanitized internal service failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Fail-closed policy blocked the request because Redis was unavailable */
            503: {
                headers: {
                    /** @description Decision responses are not cacheable */
                    "Cache-Control"?: unknown;
                    /** @description Retry delay when one is known */
                    "Retry-After"?: unknown;
                    /** @description Configured policy limit */
                    "X-RateLimit-Limit"?: unknown;
                    /** @description Decision source */
                    "X-RateLimit-Source"?: unknown;
                    /** @description Request correlation identifier */
                    "X-Request-Id"?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitCheckResponse"];
                };
            };
        };
    };
}
